import type { Metadata } from "next";
import AuthLayout from "@/layout/AuthLayout";
import DataLayout from "@/layout/DataLayout";
import Header from "@/shared/component/Header";
import { Bars3BottomLeftIcon } from "@heroicons/react/24/solid";

export const metadata: Metadata = {
  title: "Shiply",
  description: "Generated by Shiply",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigation = [
    { title: "Sales", href: "/dashboard/sales" },
    { title: "Customers", href: "/dashboard/customers" },
  ];

  return (
    <DataLayout>
      <div className="min-h-screen">
        <Header title="Dashboard" navigation={navigation} />
        <div className="drawer lg:drawer-open">
          <input id="my-drawer-4" type="checkbox" className="drawer-toggle" />
          <label
            htmlFor="my-drawer-2"
            className="btn m-2 drawer-button lg:hidden"
          >
            <Bars3BottomLeftIcon className="size-5" />
          </label>
          <div className="drawer-content flex flex-col">{children}</div>
          <div className="drawer-side">
            <label
              htmlFor="my-drawer-4"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
              {/* Sidebar content here */}
              {navigation.map((item) => (
                <li key={item.title}>
                  <a href={item.href}>{item.title}</a>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </DataLayout>
  );
}
