import type { Metadata } from "next";
import AuthLayout from "@/layout/AuthLayout";


export const metadata: Metadata = {
  title: "Shiply",
  description: "Generated by Shiply",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthLayout>
            {children}
    </AuthLayout>
  );
}
